import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "forest-deep": "#0F3E17",
        primary: "#002708",
        secondary: "#406840",
        "sage-muted": "#A3B18B",
        "surface-matcha": "#D9EBD7",
        "terracotta-accent": "#E07A5F",
        "coral-alert": "#EA580C",
        "surface-porcelain": "#FDFBF7",
        "surface-cream": "#FAF7F2",
        surface: "#F5FBF4",
        "surface-container-low": "#EFF5EE",
        "surface-container": "#E9EFE9",
        "surface-container-high": "#E4EAE3",
        "surface-container-highest": "#DEE4DD",
        "surface-sage-subtle": "#F4F7F4",
        "surface-container-lowest": "#FFFFFF",
        "surface-bright": "#F5FBF4",
        "text-primary": "#1A201C",
        "on-surface": "#171D19",
        "text-muted": "#526057",
        "on-surface-variant": "#424940",
        "border-tactile": "#E5ECE4",
        outline: "#72796F",
        "outline-variant": "#C1C9BD",
        "secondary-container": "#BEECB9",
        "primary-fixed": "#BBF0B8",
        "primary-fixed-dim": "#A0D39D",
        "on-primary": "#FFFFFF",
        "on-primary-fixed-variant": "#225027",
        "on-primary-fixed": "#002106",
        error: "#BA1A1A",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
        // Ventriloc tokens
        graphite: "#202020",
        "canvas-white": "#ffffff",
        ash: "#efefef",
        fog: "#f5f5f5",
        ivory: "#ebe6dd",
        steel: "#4d4d4d",
        slate: "#828282",
        mist: "#e8e8e8",
        "ember-orange": "#ff682c",
        brass: "#816729",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        "code-badge": ["Space Mono", "monospace"],
      },
      fontSize: {
        // Fluid type scale — clamp(min, preferred-vw, max)
        "headline-2xl": ["clamp(48px,5vw,80px)",  { lineHeight: "1.05", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-xl":  ["clamp(36px,3.6vw,60px)", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg":  ["clamp(28px,2.8vw,44px)", { lineHeight: "1.2",  letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md":  ["clamp(20px,2vw,30px)",   { lineHeight: "1.3",  fontWeight: "500" }],
        "headline-sm":  ["clamp(17px,1.6vw,24px)", { lineHeight: "1.4",  fontWeight: "500" }],
        "body-xl":      ["clamp(16px,1.4vw,22px)", { lineHeight: "1.7",  fontWeight: "400" }],
        "body-lg":      ["clamp(15px,1.2vw,19px)", { lineHeight: "1.7",  fontWeight: "400" }],
        "body-md":      ["clamp(13px,1vw,16px)",   { lineHeight: "1.6",  fontWeight: "400" }],
        "body-sm":      ["clamp(12px,0.9vw,14px)", { lineHeight: "1.5",  fontWeight: "400" }],
        "label-lg":     ["clamp(13px,1vw,16px)",   { lineHeight: "1.4",  letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md":     ["clamp(11px,0.85vw,14px)",{ lineHeight: "1.4",  letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm":     ["clamp(10px,0.75vw,12px)",{ lineHeight: "1.3",  letterSpacing: "0.04em", fontWeight: "600" }],
        "code-badge":   ["clamp(10px,0.75vw,12px)",{ lineHeight: "1.4",  letterSpacing: "0.02em", fontWeight: "400" }],
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
        "nav-pill": "200px",
        sharp: "0px",
        "asymmetric-card": "6px 0px 0px 0px",
      },
      maxWidth: {
        "8xl": "1440px",
        "9xl": "1600px",
      },
    },
  },
  plugins: [],
};
export default config;
