import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "forest-deep": "#0F3E17",
        primary: "#002708",
        secondary: "#406840",
        "sage-muted": "#A3B18B",
        "surface-matcha": "#D9EBD7",
        "terracotta-accent": "#E07A5F",
        "coral-alert": "#EA580C",
        "surface-porcelain": "#FDFBF7",
        "surface-cream": "#FAF7F2",
        surface: "#F5FBF4",
        "surface-container-low": "#EFF5EE",
        "surface-container": "#E9EFE9",
        "surface-container-high": "#E4EAE3",
        "surface-container-highest": "#DEE4DD",
        "surface-sage-subtle": "#F4F7F4",
        "surface-container-lowest": "#FFFFFF",
        "surface-bright": "#F5FBF4",
        "text-primary": "#1A201C",
        "on-surface": "#171D19",
        "text-muted": "#526057",
        "on-surface-variant": "#424940",
        "border-tactile": "#E5ECE4",
        outline: "#72796F",
        "outline-variant": "#C1C9BD",
        "secondary-container": "#BEECB9",
        "primary-fixed": "#BBF0B8",
        "primary-fixed-dim": "#A0D39D",
        "on-primary": "#FFFFFF",
        "on-primary-fixed-variant": "#225027",
        "on-primary-fixed": "#002106",
        error: "#BA1A1A",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
      },
      fontFamily: {
        headline: ["Newsreader", "Georgia", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        "code-badge": ["Space Mono", "monospace"],
      },
      fontSize: {
        "headline-2xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-xl": ["42px", { lineHeight: "50px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-xl": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "code-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
};
export default config;
