import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://medspace.ai";
  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/products/medscribe`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/products/vitalgraph`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/products/clinicops`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/products/patientgraph`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/products/clinicalkg-enterprise`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/platform/clinical-knowledge-graph`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/platform/graphrag`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/platform/ai-reasoning`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/platform/evidence-citations`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/platform/data-normalization`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/platform/apis`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/solutions/clinical-documentation`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/solutions/remote-patient-monitoring`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/solutions/clinic-operations`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/solutions/patient-engagement`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/solutions/clinical-research`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/integrations/fhir`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/integrations/hl7`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/integrations/ehr`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/integrations/medical-devices`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/integrations/communication`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/security`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/evidence`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/industries/clinics`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/industries/hospitals`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/industries/health-systems`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/industries/research`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/industries/healthcare-organizations`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/resources/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/resources/research`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/resources/case-studies`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/resources/guides`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/resources/documentation`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/company/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/company/team`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/company/careers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/company/contact`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
  ];
}
